// Portfolio items data
export const portfolioItems = [
  {
    id: "bridal-traditional",
    title: "Traditional Bridal Makeup",
    description:
      "A stunning traditional bridal look featuring rich red and gold tones that complement traditional Indian wedding attire. This look is designed to last through long ceremonies and photograph beautifully.",
    image: "/indian-bride-red.png",
    category: "Bridal",
    date: "March 2024",
    client: "Priya Sharma",
    occasion: "Traditional Hindu Wedding Ceremony",
    location: "Delhi",
    products: [
      "MAC Ruby Woo Lipstick",
      "Anastasia Beverly Hills Dipbrow Pomade",
      "Charlotte Tilbury Airbrush Flawless Foundation",
      "Huda Beauty Rose Gold Palette",
      "Kryolan Dermacolor Camouflage Cream",
    ],
    techniques: [
      "Traditional bridal eye makeup with winged liner",
      "Matte finish base with strategic highlighting",
      "Long-lasting setting techniques",
      "Waterproof application for emotional ceremonies",
    ],
    testimonial: {
      text: "Divya created the most beautiful bridal look for my wedding day. The makeup lasted through hours of ceremonies and still looked fresh in the evening. I received so many compliments!",
      author: "Priya Sharma",
    },
    relatedLooks: ["bridal-modern", "engagement-traditional", "reception-glam"],
  },
  {
    id: "bridal-modern",
    title: "Modern Bridal Makeup",
    description:
      "A contemporary bridal look featuring soft, natural tones with a luminous finish. This elegant style balances tradition with modern beauty trends for the sophisticated bride.",
    image: "/modern-bride-natural-makeup.png",
    category: "Bridal",
    date: "February 2024",
    client: "Meera Kapoor",
    occasion: "Contemporary Wedding Ceremony",
    location: "Gurgaon",
    products: [
      "Charlotte Tilbury Pillow Talk Lipstick",
      "Bobbi Brown Long-Wear Gel Eyeliner",
      "NARS Natural Radiant Longwear Foundation",
      "Pat McGrath Divine Rose Palette",
      "Laura Mercier Translucent Setting Powder",
    ],
    techniques: [
      "Soft-focus base with natural glow",
      "Defined but natural brows",
      "Subtle contouring for photogenic definition",
      "Soft smokey eye with individual lashes",
    ],
    testimonial: {
      text: "I wanted a natural look that still felt special for my wedding day, and Divya delivered perfectly. The makeup enhanced my features without feeling heavy, and the photos turned out beautifully.",
      author: "Meera Kapoor",
    },
    relatedLooks: ["bridal-traditional", "engagement-modern", "photoshoot-natural"],
  },
  {
    id: "party-glam",
    title: "Glamorous Party Makeup",
    description:
      "A bold, glamorous look perfect for evening events and celebrations. Features dramatic eyes, glowing skin, and statement lips that command attention in any room.",
    image: "/glamorous-party-makeup.png",
    category: "Party",
    date: "January 2024",
    client: "Alisha Khan",
    occasion: "New Year's Eve Gala",
    location: "NCR",
    products: [
      "Dior Backstage Face & Body Foundation",
      "Pat McGrath Mothership Palette",
      "Fenty Beauty Killawatt Highlighter",
      "Huda Beauty Liquid Matte Lipstick",
      "Benefit Precisely My Brow Pencil",
    ],
    techniques: [
      "Cut-crease eyeshadow technique",
      "Strobing for dimensional highlight",
      "Ombré lip application",
      "Baking technique for long-lasting makeup",
    ],
    testimonial: {
      text: "Divya created the most stunning look for my New Year's party. The makeup stayed perfect all night despite hours of dancing, and I received countless compliments!",
      author: "Alisha Khan",
    },
    relatedLooks: ["celebrity-event", "reception-glam", "photoshoot-editorial"],
  },
  {
    id: "fashion-editorial",
    title: "High Fashion Editorial Makeup",
    description:
      "A creative, avant-garde makeup look designed for fashion photography. This editorial style pushes boundaries with artistic techniques and bold color choices.",
    image: "/high-fashion-makeup.png",
    category: "Photoshoot",
    date: "December 2023",
    client: "Vogue India",
    occasion: "Winter Fashion Editorial",
    location: "Studio, Delhi",
    products: [
      "Danessa Myricks Colorfix",
      "Natasha Denona Metropolis Palette",
      "Kevyn Aucoin Sensual Skin Enhancer",
      "Makeup Forever Ultra HD Foundation",
      "Suva Beauty Hydra Liners",
    ],
    techniques: [
      "Graphic liner application",
      "Color blocking techniques",
      "Skin perfecting for high-definition photography",
      "Mixed media application with various textures",
    ],
    testimonial: {
      text: "Working with Divya on our winter editorial was a dream. She understood the creative direction perfectly and executed looks that translated beautifully on camera.",
      author: "Sanjay Kapoor, Photography Director",
    },
    relatedLooks: ["celebrity-event", "photoshoot-creative", "party-glam"],
  },
  {
    id: "celebrity-event",
    title: "Celebrity Red Carpet Makeup",
    description:
      "A sophisticated, camera-ready look designed for red carpet events and award shows. Features flawless skin, defined features, and a timeless elegance that photographs beautifully under all lighting conditions.",
    image: "/elegant-celebrity-makeup.png",
    category: "Celebrity",
    date: "November 2023",
    client: "Confidential",
    occasion: "Film Awards Ceremony",
    location: "Mumbai",
    products: [
      "Armani Luminous Silk Foundation",
      "Charlotte Tilbury Hollywood Flawless Filter",
      "Tom Ford Eye Color Quad",
      "Patrick Ta Major Beauty Headlines Blush",
      "Lisa Eldridge True Velvet Lipstick",
    ],
    techniques: [
      "Red carpet-specific highlighting techniques",
      "Flash photography-friendly application",
      "Long-wear setting methods for hours-long events",
      "Dimensional contouring for camera",
    ],
    testimonial: {
      text: "Divya is my go-to artist for important events. She understands how to create looks that are both stunning in person and photograph beautifully under harsh lighting.",
      author: "Anonymous Celebrity Client",
    },
    relatedLooks: ["party-glam", "photoshoot-editorial", "engagement-glam"],
  },
  {
    id: "engagement-traditional",
    title: "Traditional Engagement Makeup",
    description:
      "A vibrant, celebratory look perfect for engagement ceremonies. This style balances traditional elements with a fresh, youthful approach for the bride-to-be.",
    image: "/indian-engagement-makeup.png",
    category: "Engagement",
    date: "October 2023",
    client: "Neha Gupta",
    occasion: "Traditional Engagement Ceremony",
    location: "Gurgaon",
    products: [
      "Estée Lauder Double Wear Foundation",
      "Juvia's Place Eyeshadow Palette",
      "Rare Beauty Soft Pinch Liquid Blush",
      "Maybelline SuperStay Matte Ink Lipstick",
      "Benefit Hoola Bronzer",
    ],
    techniques: [
      "Vibrant color application for festive occasions",
      "Balanced makeup to complement heavy jewelry",
      "Sweat-proof application for dancing",
      "Strategic powder placement for flash photography",
    ],
    testimonial: {
      text: "My engagement makeup was absolutely perfect! Divya created a look that complemented my outfit beautifully and lasted through hours of ceremonies and celebrations.",
      author: "Neha Gupta",
    },
    relatedLooks: ["bridal-traditional", "party-glam", "reception-glam"],
  },
]
